### ISSUE TITLE
Video cannot be extracted since 1/24

### ISSUE THREAD

**Issue by JmyW** [naveedhassan913/YouTubeExtractor#10]
This is a good library , it worked perfect. I just changed from other to this one. 
But start from today 1/24, Youtube changed again. Many of videos can be no longer extracted.

Naveed, could you check it and share your idea and solution? Thanks in advance.

**Comment by serhathacioglu92** [comment]
Yes same issue for me:(

**Comment by nhCoder** [comment]
Please send me the links of the video

**Comment by JmyW** [comment]
For example: 
https://www.youtube.com/watch?v=eNt78mQJavY
https://www.youtube.com/watch?v=AgFeZr5ptV8
https://www.youtube.com/watch?v=-CwoylxqVPA

**Comment by nhCoder** [comment]
Lib updated and fixed

**Comment by serhathacioglu92** [comment]
Thanks Naveed, working again

**Comment by JmyW** [comment]
Super !!!
Thank you, Naveed. It works!

**Comment by JmyW** [comment]
Seems failed again today:  ☹️

https://www.youtube.com/watch?v=eNt78mQJavY
https://m.youtube.com/watch?v=AgFeZr5ptV8
https://m.youtube.com/watch?v=8sPgYRO_4v8
https://m.youtube.com/watch?v=1BQKXKL4L50

**Comment by KaustubhPatange** [comment]
@JmyW Your links are working man. It worked for me!

**Comment by nhCoder** [comment]
Seems to have a bug due to subtitles extraction

**Comment by nhCoder** [comment]
Checkout fixed!

**Comment by JmyW** [comment]
Awesome! it works again. Thanks a lot!
