### ISSUE TITLE
Hey Naveed, Thanks for offline video Youtube extraction . Can you please tell me how to play live youtube videos

### ISSUE THREAD

**Issue by yatinjulka95** [naveedhassan913/YouTubeExtractor#12]

**Comment by yatinjulka95** [comment]
Can you please tell me how to play live youtube videos. 
Updated code is not able to play Live videos

**Comment by nhCoder** [comment]
There are several links extracted....u can check  
```
isLive()
```

**Comment by yatinjulka95** [comment]
Thanks Naveed. 
Got those URL's and played in my player.

**Comment by yatinjulka95** [comment]
I really appreciate your efforts. 
All the best :)
