### ISSUE TITLE
I use the library usefully. I have a question.

### ISSUE THREAD

**Issue by yyms3275** [naveedhassan913/YouTubeExtractor#14]
I use the library usefully. I have a question. Can you control the quality and subtitles of YouTube videos through this library?

The data is imported, but I'm not sure how to use the quality settings and subtitles. Is there really an easy way to implement it or do I need to implement it myself with the data?

* Is there a way to add quality items to a MappingTrackSelector.MappedTrackInfo?

**Comment by nhCoder** [comment]
Use 
```
getQualityLabel()
```
To check quality.
