### ISSUE TITLE
extract video some urls are broken

### ISSUE THREAD

**Issue by arielv456** [naveedhassan913/YouTubeExtractor#17]
Hi,

thank a lot for your library, it's very helpful for me.

I try to extract the url: [https://www.youtube.com/watch?v=YYMlvcRgkdU](url).

and some of the urls I get back are broken.

can you please give me some info of what the problem can be?

thank in advanced.

**Comment by nhCoder** [comment]
Please explain which resolution url failed to play. I tested the url it seems to play all links..

**Comment by arielv456** [comment]
The muxedMedia always work, the problem is with adaptiveMedia there almost all of the urls don't works.
I even tried it on your test app and the problem is the same, half of the urls work and others not.

**Comment by nhCoder** [comment]
Ok i got it... Some video links duration are 0...idk why but YouTube responds with some invalid links... I had already created a method to filter invalid urls but forget😁to use.Use `Utils.filterInvalidLinks( urls) ` to get only valid urls. thanks

**Comment by arielv456** [comment]
You right this is indeed the problem.
So I just added this function and it help.. 😎.
Another problem I noticed is that `getAverageBitrate()` sometimes can come back null or 0.0 and these urls also don't work..

**Comment by nhCoder** [comment]
I guess those were the invalid links that you encountered earlier....🤔

**Comment by arielv456** [comment]
Oh no, it's a different problem.
I know that because I already fixed it to my self.

Now I change the function to:
`public static List<YTMediaModel> filterInvalidLinks(List<YTMediaModel> urls) {
        List<YTMediaModel> workingLinks = new ArrayList<>();
        for (YTMediaModel media : urls) {
            if (!media.getUrl().contains("&dur=0.0") && (media.getAverageBitrate() != null && media.getAverageBitrate() != 0.0)) {
                workingLinks.add(media);
            }
        }

        return workingLinks;
 }`

**Comment by nhCoder** [comment]
Send me the video link

**Comment by arielv456** [comment]
I don't remember what link it's was, I came across it about a month ago.
