### ISSUE TITLE
YouTube extraction not working

### ISSUE THREAD

**Issue by KaustubhPatange** [naveedhassan913/YouTubeExtractor#25]
For those who are wondering why YouTube extraction is not working again. I've submitted a PR #24 which fixes this issue. 

_Waiting for the OP to merge the request so that I'll close this issue._

**Comment by mayurss786** [comment]
Hi may be its noob question 
Can we have both cipher and signatureCipher?

**Comment by KaustubhPatange** [comment]
@mayurss786 Yes we can have that but any particular reason why?

**Comment by mayurss786** [comment]
It should be good practice till complete removal of cipher 
Because in some videos it’s still working
