### ISSUE TITLE
some links not working 

### ISSUE THREAD

**Issue by xibr** [naveedhassan913/YouTubeExtractor#3]
hi, this video link not work 

https://youtu.be/oTxd8iGHPbs

and this
https://www.youtube.com/watch?v=Vtov0u4cwBI

**Comment by JeffZane** [comment]
https://www.youtube.com/watch?v=-4fvCyJBM2Q
https://www.youtube.com/watch?v=zRcOtsI8qg0

**Comment by nhCoder** [comment]
I'll soon fix it thanks for letting me know

**Comment by JeffZane** [comment]
supply more links:
https://www.youtube.com/watch?v=CGIuBSunboo
https://www.youtube.com/watch?v=RN2brfgs_5A
https://www.youtube.com/watch?v=p7faTzv6ULs

and thank you very much for your contribution

**Comment by JeffZane** [comment]
Our project is about to be released, and if there are updates, please let me know as soon as possible,
Many thanks.

**Comment by nhCoder** [comment]
Im currently compiling the project.... Soon there will b a fix..

**Comment by nhCoder** [comment]
The bug is fixed

**Comment by JeffZane** [comment]
https://www.youtube.com/watch?v=czS-QRRBjf8

**Comment by nhCoder** [comment]
@bunaif as far as this link [https://www.youtube.com/watch?v=Vtov0u4cwBI](https://www.youtube.com/watch?v=Vtov0u4cwBI)..it is age restricted video.....The current solution is make user login through a  webview and get cookies,  set the cookies in a map with key `cookie`  and set it using `setHeaders`  method....

_Sent from my HOT 4 PRO using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by nhCoder** [comment]
@JeffZane 
The video is removed
![](https://i.imgur.com/APIx93K.png)

_Sent from my HOT 4 PRO using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by JeffZane** [comment]
Ok thanks

**Comment by JeffZane** [comment]
https://www.youtube.com/watch?v=E9YRvQtwCWo
https://www.youtube.com/watch?v=8fwlcPpNq9w
https://www.youtube.com/watch?v=SXKtr11orrQ
https://www.youtube.com/watch?v=C-IFyB8zPIU
https://www.youtube.com/watch?v=hBnrf8Y43uU

how about these links?

**Comment by nhCoder** [comment]
@JeffZane they all are working except https://m.youtube.com/watch?v=hBnrf8Y43uU which is blocked...![](https://i.imgur.com/JHZuut6.png).
Plz make sure u check before you ask? thanks

_Sent from my HOT 4 PRO using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by JeffZane** [comment]
Sorry, I just tested it in release mode.Because compilation failed, I configured the proguards which may be the reason
all failed in release mode, I'm looking for the reason

**Comment by nhCoder** [comment]
I don't know, check using the demo apk...

**Comment by JeffZane** [comment]
If you have time, you can update the proguards configuration

**Comment by nhCoder** [comment]
@JeffZane why don't u just copy the java class to your already project.

_Sent from my HOT 4 PRO using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by JeffZane** [comment]
Yes, I've copied it, but compilation failed for proguards(org.mozilla.javascript...java.awt...javax.swing...)
I configured it to compile normally, but all conversions failed.
Finally, I found that the configuration of models was less.

**Comment by JeffZane** [comment]
my proguard rules:
-keep public class javax.swing.** {*;}
-keep public class java.awt.** {*;}
-keep public class org.mozilla.javascript.** {*;}
-keep public class xxx.util.ytextractor.model.** {*;}
-dontwarn javax.swing.**
-dontwarn java.awt.**
-dontwarn org.mozilla.javascript.**
-dontwarn xxx.util.ytextractor.model.**
