### ISSUE TITLE
com.fel.example.ytextractor.ExtractorException: Error While getting Youtube Data:Attempt to get length of null array

### ISSUE THREAD

**Issue by niteshfel** [naveedhassan913/YouTubeExtractor#34]
com.fel.example.ytextractor.ExtractorException: Error While getting Youtube Data:Attempt to get length of null array
Try with this video id  = _DKifeaR5hM and also this >> S_ZCVFEXll4

**Comment by nhCoder** [comment]
Lib updated and fixed.. Check out
