### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.xyz.model.Response$Assets.getJs()' on a null object reference

### ISSUE THREAD

**Issue by craftbox2245** [naveedhassan913/YouTubeExtractor#37]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.xyz.model.Response$Assets.getJs()' on a null object reference  Please help me @naveedhassan913

**Comment by ali-nooreddine** [comment]
I have the same issue, for all the videos not only the enciphered

**Comment by Dolanpls** [comment]
Same here

**Comment by dmkenza** [comment]
I block this error by try catch. This is temp fix. Mb will be helping for someone.
We need help @naveedhassan913. Seems he is busy.

It appears in YoutubeStreamExtractor in

decodedSig = CipherManager.dechiperSig(URLDecoder.decode(partCipher.replace("s=", "")), response.getAssets().getJs());


I generate library from jitpack.
Add in your code 
  ` implementation 'com.github.dmkenza:YouTubeExtractor:0.12'`



 ` allprojects {
    repositories {
        maven { url 'https://jitpack.io' }
    }
}`

@naveedhassan913 please, use new Android Studio with new Gradle. Your gradle so old.
Use as well jitpack.io for publish builds.

**Comment by hhyeok1026** [comment]
@dmkenza 

I've seen your cloned repository.
(https://github.com/dmkenza/YouTubeExtractor/blob/master/YoutubeExtractor/app/src/main/java/com/naveed/ytextractor/YoutubeStreamExtractor.java)

You have a try catch inside the try catch that already exists.
An error occurs on that line,
It falls to the same exception in the inner try catch.

**This was not a temporary help.**
Also, I am not printing the errorstack in the catch statement. It's hard to figure out what the exception is later on.

**Comment by hhyeok1026** [comment]
The current problem is that assets have no value.


I think this will be the solution.
**https://github.com/sealedtx/java-youtube-downloader/commit/8a86aa2745f50575d947461981ce488b01c78af7**

This gives a request to "https://www.youtube.com/embed/" + videoId,
I checked that a response with "assets-js" comes out.

However, it seems that the part to be parsed needs to be different.
It seems that the variable names that need to be parsed are different.

**Comment by Dolanpls** [comment]
@naveedhassan913 is this repo abandoned? this is a real bug and we can't extract any video.
Please, at least answer us to know if you are working on it, thanks

**Comment by yyms3275** [comment]
Has anyone solved this problem?

**Comment by nhCoder** [comment]
@Dolanpls i will try to push an update
