### ISSUE TITLE
Response$Assets.getJs()' on a null object reference error!

### ISSUE THREAD

**Issue by yyms3275** [naveedhassan913/YouTubeExtractor#38]
Has anyone solved the following problems? 

onExtractionGoesWrong : Attempt to invoke virtual method 'java.lang.String com.test.player.Model.Response$Assets.getJs()' on a null object reference

**Comment by Dolanpls** [comment]
Same issue reported in https://github.com/naveedhassan913/YouTubeExtractor/issues/37 
@naveedhassan913 said that he will try to update with this fix
