### ISSUE TITLE
i like this repo but i need to extract audio link from youtube

### ISSUE THREAD

**Issue by waqarr** [naveedhassan913/YouTubeExtractor#4]
i like this repo but i need to extract audio link from youtube

**Comment by waqarr** [comment]
how can i extract m4a audio link ?

**Comment by nhCoder** [comment]
@waqarr 
Use this code under `onExtractionDone` .

```
for(YoutubeMedia media:adativeStream){
													   if(media.isAudioOnly()){
														   ....
													   }
												   }
```



_Sent from my HOT 4 PRO using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by xibr** [comment]
if i want show all Resolution how can i do that?

like this 

`for(YoutubeMedia media:muxedStream){`
                          ` if(!media.isAudioOnly() && !media.isVideoOnly()) {`
                            `addButtonToMainLayout(media.getResolution(), media.getUrl(), meta.getTitle());`
                               ` }`
                            `}`

this return null `media.getResolution()`

**Comment by nhCoder** [comment]
@bunaif  isVideoOnly  is enough..


_Sent from my HOT 4 PRO using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by nhCoder** [comment]
@bunaif  As far as `media.getResolution() ` it works only with videos.. It will return null for audios 

_Sent from my HOT 4 PRO using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by xibr** [comment]
@naveedhassan913  I know, but still give me a null.

Can you check them?

**Comment by nhCoder** [comment]
Actually I'm too busy these days, So there is less possibilities that i update the lib.Why don't unit fork lib and fix these issues yourself.

**Comment by xibr** [comment]
okay, I will try.
Thank you

**Comment by xibr** [comment]
@naveedhassan913 fixed, now return hd720 or medium
[https://github.com/bunaif/YouTubeExtractor/commit/e66d48241ac944c6657b55d9f186c10a5a9080f5](https://github.com/bunaif/YouTubeExtractor/commit/e66d48241ac944c6657b55d9f186c10a5a9080f5)

check it.
![Screenshot_20190805-221801_ ](https://user-images.githubusercontent.com/20098154/62486348-11ba1880-b7d0-11e9-8ffc-d20a234f2413.jpg)

**Comment by nhCoder** [comment]
Lib updated... Use getMimeType() to differ audio /video
