### ISSUE TITLE
this song is not downloading

### ISSUE THREAD

**Issue by mrhussnain** [naveedhassan913/YouTubeExtractor#5]
hy some songs are not downloading can you please update the api...thanks

https://www.youtube.com/watch?v=7o9Nc9dANzs

**Comment by nhCoder** [comment]
This is a age restricted video.. You can set login cookies by using setHeaders method.first u have to prompt a user to login into their google account using a webview.. Then get the cookies for website : youtube.com ..thanks

**Comment by mrhussnain** [comment]
is there any other way except web view ??

**Comment by nhCoder** [comment]
Added for age restricted videos
