### ISSUE TITLE
Thank you for the code. The Age Restricted Extraction failed for this video

### ISSUE THREAD

**Issue by simonho1989** [naveedhassan913/YouTubeExtractor#8]
https://www.youtube.com/watch?v=2UltvQ1nkuM

**Comment by simonho1989** [comment]
Sorry my bad. It's working. Didn't realize to use useDefaultLogin()
Will the cookies string ever be changed or expired?

**Comment by nhCoder** [comment]
I recommend to use your own Google account cookies...

**Comment by simonho1989** [comment]
Sorry I dont have much knowledge on this. May I ask how do I find my cookie?
